# Generated by Django 3.2.8 on 2021-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='No.')),
                ('code', models.IntegerField(verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='品名')),
                ('quantity', models.IntegerField(blank=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='単位')),
                ('order', models.DateField(blank=True, verbose_name='発注日')),
                ('prefer', models.DateField(blank=True, verbose_name='希望納期')),
                ('fixed', models.DateField(blank=True, verbose_name='確定納期')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
    ]
