# Generated by Django 3.2.9 on 2021-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='fixed',
            field=models.DateField(blank=True, null=True, verbose_name='確定納期'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='order',
            field=models.DateField(blank=True, null=True, verbose_name='発注日'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prefer',
            field=models.DateField(blank=True, null=True, verbose_name='希望納期'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='単位'),
        ),
    ]
