# Generated by Django 3.2.8 on 2021-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_auto_20211110_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
        ),
        migrations.AlterField(
            model_name='progress',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='No.'),
        ),
    ]
