# Generated by Django 3.2.8 on 2021-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_auto_20211114_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
        ),
    ]
