# Generated by Django 3.2.8 on 2021-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_auto_20211117_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('client', models.CharField(blank=True, max_length=30, null=True, verbose_name='見積先')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='品名')),
                ('form', models.CharField(blank=True, max_length=30, null=True, verbose_name='形態')),
                ('deadline', models.CharField(blank=True, max_length=30, null=True, verbose_name='企画期限')),
                ('requester', models.CharField(blank=True, max_length=30, null=True, verbose_name='依頼部門')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('responder', models.TextField(blank=True, null=True, verbose_name='担当者')),
            ],
        ),
    ]
