# Generated by Django 3.2.8 on 2022-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='依頼元')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('responder', models.TextField(blank=True, null=True, verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='依頼先')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('responder', models.TextField(blank=True, null=True, verbose_name='担当者')),
            ],
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
    ]
