# Generated by Django 3.2.8 on 2022-11-25 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_auto_20221126_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='description',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='prefer',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='unit',
        ),
        migrations.AddField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
