# Generated by Django 3.2.8 on 2022-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_auto_20221126_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Progress',
            new_name='ProgressNB',
        ),
    ]
