# Generated by Django 3.2.8 on 2023-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_auto_20221126_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods46',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='No.')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='コード')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='内容')),
                ('supplier', models.CharField(blank=True, max_length=30, null=True, verbose_name='仕入先')),
                ('cutomer', models.CharField(blank=True, max_length=30, null=True, verbose_name='得意先')),
                ('description', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('writer', models.CharField(blank=True, max_length=30, null=True, verbose_name='依頼書作成')),
                ('register', models.CharField(blank=True, max_length=30, null=True, verbose_name='カクテル登録')),
                ('update', models.CharField(blank=True, max_length=30, null=True, verbose_name='リスト更新')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
